language: c

sudo: true

matrix:
  include:
  - compiler: clang
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.6
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
        - clang-3.6
        - libjansson-dev
        - valgrind
        - cppcheck
        - lcov
        - cmake
        - cmake-data
    env: CC="clang-3.6" CXX="clang++-3.6"
  - compiler: gcc
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
        - gcc-6
        - g++-6
        - libjansson-dev
        - valgrind
        - cppcheck
        - lcov
        - cmake
        - cmake-data
    env: CC="gcc-6" CXX="g++-6"
  - env: ARCH=arm
    addons:
      apt:
        sources:
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
        - gcc-arm-linux-gnueabihf
        - libc6-dev-armhf-cross
        - cmake
        - cmake-data

script:
  - "bash -ex .travis-qemu.sh"

notifications:
  email: false

addons:
  artifacts:
    s3_region: "us-west-2"
    paths: "*.deb"
    debug: true